//! Error types generated by an MPC constraint system

use core::fmt::Display;
use std::error::Error;

/// The error type emitted by MPC circuit operations
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum MpcCircuitError {}

impl Display for MpcCircuitError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{self:?}")
    }
}
impl Error for MpcCircuitError {}
